### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/entrevista-entrevista#2]
[REPORTE DE ENTREVISTA_S1.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-entrevista/files/7133644/REPORTE.DE.ENTREVISTA_S1.pdf)

**Comment by Anthony4523** [comment]
Calificación = 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
